name: floorplan-thesis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - matplotlib
  - numpy
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - seaborn
  - shapely
  - rasterio
  - huggingface_hub
  - datasets
  - pip
  - omegaconf
  - scipy=1.10.1
  - pip:
    - rplanpy